/**
 * mockData.ts — All static mock data for the Strategy War Room.
 */

import type { StrategyWarRoomData } from './types';

const now = new Date();
const minsAgo = (m: number) => new Date(now.getTime() - m * 60_000);

export const MOCK_WAR_ROOM: StrategyWarRoomData = {

  // ── Concept Brief ────────────────────────────────────────────────────────────
  brief: {
    projectTitle: 'The Rise of AI in Healthcare',
    rawIdea:
      'A documentary-style YouTube series uncovering how AI is transforming diagnostics, drug discovery, and patient care — told through real clinician stories and AI demos.',
    targetAudience: 'Tech-savvy healthcare professionals & health-tech investors, 28–50',
    platform: 'YouTube (Primary) · LinkedIn (Amplification)',
    goal: 'Brand authority + Lead generation for health-tech SaaS',
    budget: '$12,000 – $18,000',
    timeline: '8 weeks end-to-end',
    references: [
      { label: 'AI in Diagnostics 2024 — McKinsey Report', url: '#' },
      { label: 'Stanford Medicine AI Study', url: '#' },
      { label: 'WHO Digital Health Strategy', url: '#' },
    ],
  },

  // ── AI Agents ─────────────────────────────────────────────────────────────
  agents: [
    {
      id: 'creative-director',
      name: 'Nova',
      role: 'Creative Director',
      color: '#8B5CF6',
      initials: 'ND',
      status: 'completed',
      confidencePct: 88,
      contributionPct: 22,
      agreementLevel: 'agree',
      currentFocus: 'Finalising narrative arc structure',
      model: 'GPT-4o Creative',
    },
    {
      id: 'risk-critic',
      name: 'Rex',
      role: 'Risk Critic',
      color: '#EF4444',
      initials: 'RC',
      status: 'completed',
      confidencePct: 76,
      contributionPct: 18,
      agreementLevel: 'partial',
      currentFocus: 'Budget feasibility re-evaluation',
      model: 'Claude 3.5 Sonnet',
    },
    {
      id: 'audience-strategist',
      name: 'Aria',
      role: 'Audience Strategist',
      color: '#06B6D4',
      initials: 'AS',
      status: 'reviewing',
      confidencePct: 91,
      contributionPct: 16,
      agreementLevel: 'agree',
      currentFocus: 'Validating viewer persona depth',
      model: 'GPT-4o',
    },
    {
      id: 'marketing-strategist',
      name: 'Max',
      role: 'Marketing Strategist',
      color: '#10B981',
      initials: 'MS',
      status: 'completed',
      confidencePct: 84,
      contributionPct: 19,
      agreementLevel: 'agree',
      currentFocus: 'Distribution funnel optimisation',
      model: 'GPT-4o',
    },
    {
      id: 'technical-expert',
      name: 'Zara',
      role: 'Technical Expert',
      color: '#F59E0B',
      initials: 'TE',
      status: 'thinking',
      confidencePct: 79,
      contributionPct: 12,
      agreementLevel: 'neutral',
      currentFocus: 'Production stack complexity assessment',
      model: 'Gemini 1.5 Pro',
    },
    {
      id: 'platform-specialist',
      name: 'Pixel',
      role: 'Platform Specialist',
      color: '#EC4899',
      initials: 'PS',
      status: 'completed',
      confidencePct: 87,
      contributionPct: 8,
      agreementLevel: 'agree',
      currentFocus: 'YouTube algorithm optimisation',
      model: 'GPT-4o Mini',
    },
    {
      id: 'ethics-auditor',
      name: 'Ethos',
      role: 'Ethics & Brand Safety',
      color: '#F97316',
      initials: 'EA',
      status: 'responding',
      confidencePct: 82,
      contributionPct: 5,
      agreementLevel: 'partial',
      currentFocus: 'Medical claims compliance review',
      model: 'Claude 3 Haiku',
    },
  ],

  // ── Debate ────────────────────────────────────────────────────────────────
  debate: {
    runState: 'paused',
    stage: 'rebuttal',
    currentRound: 3,
    totalRounds: 5,
    consensusPct: 74,
    remainingQuestions: 3,
    elapsedSeconds: 847,
    messages: [
      {
        id: 'msg-1',
        agentId: 'creative-director',
        type: 'proposal',
        round: 1,
        timestamp: minsAgo(14),
        message:
          'I propose a 6-episode mini-series. Each episode centres on one clinician using AI in a specific discipline — radiology, oncology, mental health, surgery, primary care, drug discovery. Narrative-driven, cinematic in tone. Opens with a human story, then the AI reveal. This maximises emotional hook and shareability.',
        confidence: 88,
        evidences: [
          { label: 'Netflix Doc Retention Study', source: 'Internal benchmark' },
          { label: 'Healthcare LinkedIn engagement +340%', source: 'HubSpot 2024' },
        ],
        suggestedPivot: undefined,
      },
      {
        id: 'msg-2',
        agentId: 'risk-critic',
        type: 'challenge',
        round: 1,
        timestamp: minsAgo(12),
        message:
          'I challenge the 6-episode format on budget grounds. $12–18k for 6 episodes means $2–3k per episode. Cinematic quality at that budget is unrealistic. You will either sacrifice quality or overrun. I recommend piloting with 2 episodes to validate the format before committing to 6.',
        confidence: 76,
        evidences: [
          { label: 'Production cost benchmarks Q1 2024', source: 'CreativeMind internal' },
        ],
        referencesMessageId: 'msg-1',
        objectsToId: 'msg-1',
        suggestedPivot: 'Pilot 2 episodes, then scale based on retention data',
      },
      {
        id: 'msg-3',
        agentId: 'marketing-strategist',
        type: 'response',
        round: 1,
        timestamp: minsAgo(11),
        message:
          'Rex raises a valid concern, but I\'d argue the bigger risk is launching with only 2 episodes — the algorithm needs volume to surface the series. A 4-episode arc is the sweet spot: enough content to establish a pattern, manageable on this budget if we reduce per-episode scope slightly.',
        confidence: 84,
        evidences: [
          { label: 'YouTube series algorithm study', source: 'Backlinko 2024' },
        ],
        referencesMessageId: 'msg-2',
        agreesWithId: 'msg-2',
        suggestedPivot: '4-episode series, slightly reduced scope per episode',
      },
      {
        id: 'msg-4',
        agentId: 'audience-strategist',
        type: 'agreement',
        round: 2,
        timestamp: minsAgo(9),
        message:
          'I strongly agree with Nova\'s narrative-first approach. The clinician-story opener is critical for the 28–50 professional audience — they self-identify with peers, not technology. The emotional hook is the access point. What I\'d add: each episode must end with a specific, actionable insight for the viewer\'s own practice.',
        confidence: 91,
        evidences: [
          { label: 'B2B healthcare video consumption study', source: 'LinkedIn Marketing Solutions' },
        ],
        referencesMessageId: 'msg-1',
        agreesWithId: 'msg-1',
      },
      {
        id: 'msg-5',
        agentId: 'ethics-auditor',
        type: 'flag',
        round: 2,
        timestamp: minsAgo(7),
        message:
          'Flagging a compliance risk: any medical claims or AI diagnostic accuracy statistics shown must be accompanied by appropriate disclaimers. Several competitors have had content flagged or demonetised for unsubstantiated clinical claims. I recommend a medical legal review before episode 1 publishes. This is non-negotiable.',
        confidence: 82,
        evidences: [
          { label: 'YouTube Medical Content Policy 2024', source: 'YouTube Help Centre' },
          { label: 'FTC Health Claims Guidelines', source: 'FTC.gov' },
        ],
        referencesMessageId: 'msg-3',
        suggestedPivot: 'Add a compliance review step in pre-production',
      },
      {
        id: 'msg-6',
        agentId: 'platform-specialist',
        type: 'response',
        round: 2,
        timestamp: minsAgo(6),
        message:
          'Ethos is right on compliance. Additionally, YouTube\'s medical content policy flags channels that make diagnostic claims. I recommend framing each episode as "observational" — showing AI tools in use, not endorsing them as clinically superior. Adds 0 production cost, eliminates the demonetisation risk.',
        confidence: 87,
        evidences: [
          { label: 'YouTube Health Content Best Practices', source: 'YouTube Creator Academy' },
        ],
        referencesMessageId: 'msg-5',
        agreesWithId: 'msg-5',
      },
      {
        id: 'msg-7',
        agentId: 'creative-director',
        type: 'revision',
        round: 3,
        timestamp: minsAgo(3),
        message:
          'Accepted. Revising the proposal: 4 episodes (not 6), observational framing, one actionable insight per episode, compliance review added to pre-production. I maintain the cinematic narrative structure — this is where the differentiation lives. Budget redistributed: 40% to filming, 30% to post-production, 20% to distribution, 10% to compliance review.',
        confidence: 90,
        evidences: [
          { label: 'Revised production budget model', source: 'Internal' },
        ],
        referencesMessageId: 'msg-5',
        suggestedPivot: undefined,
      },
    ],
  },

  // ── Scorecards ───────────────────────────────────────────────────────────
  scorecards: [
    {
      id: 'originality',
      label: 'Originality',
      score: 82,
      trend: 4,
      explanation: 'Clinician-first narrative angle is differentiated from existing AI explainer content.',
      improvement: 'Add a unique visual AI visualisation technique to further separate from competitors.',
      color: '#8B5CF6',
      agentId: 'creative-director',
    },
    {
      id: 'feasibility',
      label: 'Feasibility',
      score: 71,
      trend: 8,
      explanation: 'Revised 4-episode format fits the budget with a 15% contingency buffer remaining.',
      improvement: 'Lock clinician partnerships earlier to reduce scheduling risk.',
      color: '#10B981',
      agentId: 'risk-critic',
    },
    {
      id: 'audience-fit',
      label: 'Audience Fit',
      score: 91,
      trend: 2,
      explanation: 'Peer-to-peer storytelling resonates strongly with healthcare professionals aged 28–50.',
      improvement: 'Add a LinkedIn micro-content layer targeting C-suite health executives.',
      color: '#06B6D4',
      agentId: 'audience-strategist',
    },
    {
      id: 'emotional-strength',
      label: 'Emotional Strength',
      score: 86,
      trend: 5,
      explanation: 'Clinician stories create strong emotional access points. Patient outcome moments are high-impact.',
      improvement: 'Include one failure-to-success arc to increase emotional range.',
      color: '#EC4899',
      agentId: 'creative-director',
    },
    {
      id: 'trend-relevance',
      label: 'Trend Relevance',
      score: 94,
      trend: 12,
      explanation: 'AI in healthcare trending +270% this week. Optimal publish window is Q2 2025.',
      improvement: 'Tie episode 2 to a specific breaking AI healthcare news cycle.',
      color: '#F59E0B',
      agentId: 'marketing-strategist',
    },
    {
      id: 'production-complexity',
      label: 'Production Complexity',
      score: 62,
      trend: -6,
      explanation: 'Hospital filming permissions and clinical environment logistics add significant complexity.',
      improvement: 'Pre-sign filming agreements with 2 partner hospitals before production kicks off.',
      color: '#EF4444',
      agentId: 'technical-expert',
    },
    {
      id: 'brand-safety',
      label: 'Brand Safety',
      score: 78,
      trend: 7,
      explanation: 'Observational framing mitigates most risks. Compliance review step now in plan.',
      improvement: 'Complete medical-legal review before any episode enters post-production.',
      color: '#F97316',
      agentId: 'ethics-auditor',
    },
  ],

  // ── Decision Ledger ──────────────────────────────────────────────────────
  ledger: [
    {
      id: 'ld-1',
      round: 1,
      originalIdea: '6-episode documentary series',
      criticismRaised: 'Budget insufficient for 6 high-quality episodes at $2–3k each',
      changeMade: 'Reduced to 4-episode series with tighter scope per episode',
      reason: 'Maintains series volume for algorithm while staying within $18k ceiling',
      approvedBy: ['risk-critic', 'marketing-strategist', 'creative-director'],
      finalImpact: 'positive',
      impactLabel: 'Reduces overrun risk by ~40%',
    },
    {
      id: 'ld-2',
      round: 2,
      originalIdea: 'Make direct AI diagnostic accuracy claims in episodes',
      criticismRaised: 'Violates YouTube medical content policy and FTC guidelines',
      changeMade: 'Switched to observational framing — showing AI tools, not endorsing diagnostics',
      reason: 'Protects channel monetisation and brand reputation at zero production cost',
      approvedBy: ['ethics-auditor', 'platform-specialist', 'creative-director'],
      finalImpact: 'positive',
      impactLabel: 'Eliminates demonetisation risk',
    },
    {
      id: 'ld-3',
      round: 2,
      originalIdea: 'Launch all episodes simultaneously',
      criticismRaised: 'Simultaneous launch wastes the algorithm growth window',
      changeMade: 'Weekly release cadence with 2-week pre-launch promo window',
      reason: 'Maximises YouTube subscriber growth and watch-time signals per episode',
      approvedBy: ['platform-specialist', 'marketing-strategist'],
      finalImpact: 'positive',
      impactLabel: 'Est. +55% channel growth vs simultaneous launch',
    },
    {
      id: 'ld-4',
      round: 3,
      originalIdea: 'Internal production team only',
      criticismRaised: 'Hospital access and clinical filming permits require specialist experience',
      changeMade: 'Bring in one specialist medical video production coordinator',
      reason: 'Reduces filming permission delays and avoids compliance mistakes on set',
      approvedBy: ['technical-expert', 'risk-critic'],
      finalImpact: 'neutral',
      impactLabel: 'Adds ~$2k cost, saves est. 3 weeks of delays',
    },
  ],

  // ── Right Panel Decision ──────────────────────────────────────────────────
  decision: {
    overallRecommendation:
      'Proceed with the 4-episode observational documentary series. The revised scope is financially viable, strategically differentiated, and algorithmically optimised for the target audience. Begin pre-production immediately: lock clinician partners, secure filming permissions, engage compliance reviewer.',
    projectHealthPct: 81,
    risks: [
      {
        id: 'r-1',
        label: 'Hospital Filming Access',
        description: 'Permits can take 4–6 weeks. Any delay cascades through the 8-week timeline.',
        level: 'high',
        owner: 'technical-expert',
      },
      {
        id: 'r-2',
        label: 'Medical Claims Compliance',
        description: 'Unreviewed clinical statements could trigger demonetisation post-launch.',
        level: 'medium',
        owner: 'ethics-auditor',
      },
      {
        id: 'r-3',
        label: 'Budget Contingency',
        description: 'Only 15% contingency remains after scope revision. No room for scope creep.',
        level: 'medium',
        owner: 'risk-critic',
      },
    ],
    opportunities: [
      {
        id: 'op-1',
        label: 'Trend Timing',
        description: 'AI in healthcare at peak search volume. First-mover advantage available now.',
        potentialImpact: '+40% organic reach in first 30 days',
      },
      {
        id: 'op-2',
        label: 'LinkedIn Amplification',
        description: 'B2B healthcare content performs 3× better on LinkedIn with micro-clips.',
        potentialImpact: 'est. 2,400 additional qualified leads per episode',
      },
      {
        id: 'op-3',
        label: 'Hospital Partner Co-branding',
        description: 'Filming partners can become co-promotion vehicles, distributing to staff networks.',
        potentialImpact: 'Free distribution to 10,000+ healthcare professionals',
      },
    ],
    recommendedNextStep: 'Proceed to Research Lab — verify all clinical AI statistics, identify 4 filming partner hospitals, and brief the compliance reviewer on episode 1 script.',
  },
};
